/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* */
/* #undef APC_FCNTL_LOCKS */

/* */
/* #undef APC_FILEHITS */

/* */
#define APC_HAVE_LOOKUP_HOOKS 0

/* shm/mmap memory protection */
/* #undef APC_MEMPROTECT */

/* */
#define APC_MMAP 1

/* */
#define APC_PTHREADMUTEX_LOCKS 1

/* */
/* #undef APC_PTHREADRW_LOCKS */

/* */
/* #undef APC_SEM_LOCKS */

/* */
/* #undef APC_SPIN_LOCKS */

/* Whether to build apc as dynamic module */
#define COMPILE_DL_APC 1

/* */
#define HAVE_APC 1

/* Define this if your target compiler supports builtin atomics */
#define HAVE_ATOMIC_OPERATIONS 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* */
#define HAVE_SEMUN 0

/* Define to 1 if you have the `sigaction' function. */
#define HAVE_SIGACTION 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* enable valgrind memchecks */
#define HAVE_VALGRIND_MEMCHECK_H 1

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* */
/* #undef __DEBUG_APC__ */
